import { z } from "zod";
import { parseYouTubeVideoId } from "../../shared/youtube/url";

export { parseYouTubeVideoId };

export const youtubeImportSchema = z.object({
  url: z.string().trim().min(1, "YouTube video URL is required").max(2048).refine(
    (val) => Boolean(parseYouTubeVideoId(val)),
    { message: "Enter an individual YouTube video URL" }
  ),
  connectionId: z.string().min(1).max(128),
  refresh: z.boolean().default(false),
}).strict();

export const youtubeRefreshDocumentSchema = z.object({
  action: z.literal("refresh-document"),
  documentId: z.string().min(1).max(128),
}).strict();

export const youtubeRequestSchema = z.discriminatedUnion("action", [
  youtubeImportSchema.extend({ action: z.literal("preview") }).strict(),
  youtubeImportSchema.extend({ action: z.literal("import") }).strict(),
  youtubeRefreshDocumentSchema,
]);
export const youtubeDisconnectSchema = z.object({ connectionId: z.string().min(1).max(128) }).strict();
export const youtubePreviewSchema = z.object({
  videoId: z.string(), title: z.string(), channelId: z.string(), channelTitle: z.string(),
  captionId: z.string(), language: z.string(), isAutoGenerated: z.boolean(), captionUpdatedAt: z.string(),
  alreadyIndexed: z.boolean(),
});
export const youtubeStateSchema = z.object({
  configured: z.boolean(),
  connections: z.array(z.object({ id: z.string(), channelId: z.string(), channelTitle: z.string(), status: z.string() })),
  jobs: z.array(z.object({
    id: z.string(), status: z.string(), stage: z.string().nullable(), error: z.string().nullable(),
    videoId: z.string(), connectionId: z.string().nullable(),
    segmentsTotal: z.number().int().nonnegative(), segmentsSucceeded: z.number().int().nonnegative(), segmentsFailed: z.number().int().nonnegative(),
  })),
});

export type YouTubeImportInput = z.infer<typeof youtubeImportSchema>;
export type YouTubePreview = z.infer<typeof youtubePreviewSchema>;
export type YouTubeState = z.infer<typeof youtubeStateSchema>;
export const youtubeExtractedQuestionSchema = z.object({
  text: z.string().trim().min(1),
  startSeconds: z.number().finite().nonnegative(),
  endSeconds: z.number().finite().nonnegative(),
  topics: z.array(z.string()),
  proposedTopics: z.array(z.string()),
}).strict().refine((question) => question.endSeconds >= question.startSeconds, {
  message: "Question endSeconds must not precede startSeconds",
});

export const youtubeQuestionsArtifactSchema = z.object({
  version: z.literal(1),
  videoId: z.string().min(1),
  title: z.string(),
  sourceUrl: z.url(),
  extractionVersion: z.string().min(1),
  chunkingVersion: z.string().min(1),
  questions: z.array(youtubeExtractedQuestionSchema),
}).strict();

export type YouTubeExtractedQuestion = z.infer<typeof youtubeExtractedQuestionSchema>;
export type YouTubeQuestionsArtifact = z.infer<typeof youtubeQuestionsArtifactSchema>;
export type YouTubeRefreshDocumentInput = z.infer<typeof youtubeRefreshDocumentSchema>;
export type YouTubeRequest = z.infer<typeof youtubeRequestSchema>;
