"use client";

import { useRef, useState } from "react";
import {
  AlertCircle,
  BookOpen,
  CheckCircle2,
  FileCode,
  FileSpreadsheet,
  FileText,
  Layers,
  Link2,
  Plus,
  RefreshCw,
  Trash2,
  Upload,
  Video,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Spinner } from "@/components/ui/spinner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import type { ConnectorInfo } from "./types";

type UploadQueueItem = {
  id: string;
  file: File;
  status: "pending" | "uploading" | "done" | "error";
  error?: string;
};

type YouTubePreviewData = {
  videoId: string;
  title: string;
  channelId: string;
  channelTitle: string;
  captionId: string;
  language: string;
  isAutoGenerated: boolean;
  captionUpdatedAt: string;
  alreadyIndexed: boolean;
};

const SUPPORTED_EXTS = ["pdf", "docx", "doc", "pptx", "ppsx", "csv", "txt", "md"];
const ACCEPT_STRING =
  ".pdf,.docx,.doc,.pptx,.ppsx,.csv,.txt,.md,text/plain,text/markdown,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.presentationml.presentation,text/csv";

function formatBytes(n: number) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

export function KnowledgeAddSourceDialog({
  open,
  onOpenChange,
  connectors,
  onSuccess,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  connectors?: ConnectorInfo;
  onSuccess: () => void;
}) {
  const [activeTab, setActiveTab] = useState<string>("upload");

  // File Upload State
  const [queue, setQueue] = useState<UploadQueueItem[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Notion State
  const [notionMode, setNotionMode] = useState<"oauth" | "public">("oauth");
  const [notionConnectionId, setNotionConnectionId] = useState<string>("");
  const [notionUrl, setNotionUrl] = useState<string>("");
  const [notionImporting, setNotionImporting] = useState(false);

  // YouTube State
  const [youtubeConnectionId, setYoutubeConnectionId] = useState<string>("");
  const [youtubeUrl, setYoutubeUrl] = useState<string>("");
  const [youtubePreviewing, setYoutubePreviewing] = useState(false);
  const [youtubePreview, setYoutubePreview] = useState<YouTubePreviewData | null>(null);
  const [youtubeImporting, setYoutubeImporting] = useState(false);

  // Disconnect Confirmation State
  const [disconnectItem, setDisconnectItem] = useState<{
    id: string;
    title: string;
    provider: "notion" | "youtube";
  } | null>(null);
  const [disconnecting, setDisconnecting] = useState(false);

  // Helper to get active connections
  const notionConnections = connectors?.notion.connections ?? [];
  const youtubeConnections = connectors?.youtube.connections ?? [];
  const selectedNotionConnection =
    notionConnections.find((c) => c.id === notionConnectionId) ?? notionConnections[0];
  const selectedYoutubeConnection =
    youtubeConnections.find((c) => c.id === youtubeConnectionId) ?? youtubeConnections[0];

  function addFiles(files: FileList | File[]) {
    const newItems: UploadQueueItem[] = [];
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const ext = file.name.split(".").pop()?.toLowerCase() || "";
      if (!SUPPORTED_EXTS.includes(ext)) {
        toast.error(`Unsupported format: ${file.name}`);
        continue;
      }
      newItems.push({
        id: `${file.name}-${Date.now()}-${i}`,
        file,
        status: "pending",
      });
    }
    setQueue((prev) => [...prev, ...newItems]);
  }

  function removeItem(id: string) {
    if (isUploading) return;
    setQueue((prev) => prev.filter((item) => item.id !== id));
  }

  async function startUpload() {
    if (queue.length === 0 || isUploading) return;
    setIsUploading(true);
    let successCount = 0;
    let failCount = 0;

    for (let i = 0; i < queue.length; i++) {
      const item = queue[i];
      if (item.status === "done") continue;

      setQueue((prev) =>
        prev.map((q, idx) => (idx === i ? { ...q, status: "uploading" } : q)),
      );

      try {
        const formData = new FormData();
        formData.append("file", item.file);

        const res = await fetch("/api/knowledge/upload", {
          method: "POST",
          body: formData,
        });
        const data = await res.json().catch(() => null);

        if (!res.ok) {
          throw new Error(data?.error || "Upload failed");
        }

        setQueue((prev) =>
          prev.map((q, idx) => (idx === i ? { ...q, status: "done" } : q)),
        );
        successCount++;
      } catch (err) {
        failCount++;
        setQueue((prev) =>
          prev.map((q, idx) =>
            idx === i
              ? {
                  ...q,
                  status: "error",
                  error: err instanceof Error ? err.message : "Upload failed",
                }
              : q,
          ),
        );
      }
    }

    setIsUploading(false);
    if (successCount > 0) {
      toast.success(
        `Uploaded ${successCount} file${successCount > 1 ? "s" : ""}. Processing in background.`,
      );
      onSuccess();
    }
    if (failCount > 0) {
      toast.error(`Failed to upload ${failCount} file${failCount > 1 ? "s" : ""}`);
    }
  }

  async function startNotionOAuth() {
    try {
      const res = await fetch("/api/connectors/notion/oauth/start", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to start Notion authorization");
      if (data.url) {
        window.location.href = data.url;
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to connect Notion");
    }
  }

  async function startYouTubeOAuth() {
    try {
      const res = await fetch("/api/connectors/youtube/oauth/start", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to start YouTube authorization");
      if (data.url) {
        window.location.href = data.url;
      }
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to connect YouTube");
    }
  }

  async function handleNotionImport() {
    const url = notionUrl.trim();
    if (!url) {
      toast.error("Please enter a Notion page URL");
      return;
    }

    if (notionMode === "oauth" && !selectedNotionConnection) {
      toast.error("Please connect a Notion workspace first");
      return;
    }

    setNotionImporting(true);
    try {
      const body =
        notionMode === "oauth"
          ? { mode: "oauth", url, connectionId: selectedNotionConnection?.id }
          : { mode: "public", url };

      const res = await fetch("/api/knowledge/connectors/notion", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json().catch(() => null);

      if (!res.ok) throw new Error(data?.error || "Import failed");

      toast.success("Notion sync queued. Page and child pages are being indexed.");
      setNotionUrl("");
      onOpenChange(false);
      onSuccess();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Notion import failed");
    } finally {
      setNotionImporting(false);
    }
  }

  async function handleYouTubePreview() {
    const url = youtubeUrl.trim();
    if (!url) {
      toast.error("Please enter a YouTube video URL");
      return;
    }

    if (!selectedYoutubeConnection) {
      toast.error("Please connect a YouTube channel first");
      return;
    }

    setYoutubePreviewing(true);
    setYoutubePreview(null);
    try {
      const res = await fetch("/api/knowledge/connectors/youtube/preview", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          connectionId: selectedYoutubeConnection.id,
          url,
        }),
      });
      const data = await res.json().catch(() => null);

      if (!res.ok) throw new Error(data?.error || "Preview failed");

      setYoutubePreview(data);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "YouTube preview failed");
    } finally {
      setYoutubePreviewing(false);
    }
  }

  async function handleYouTubeImport() {
    const url = youtubeUrl.trim();
    if (!url || !selectedYoutubeConnection) return;

    setYoutubeImporting(true);
    try {
      const res = await fetch("/api/knowledge/connectors/youtube", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          connectionId: selectedYoutubeConnection.id,
          url,
          refresh: Boolean(youtubePreview?.alreadyIndexed),
        }),
      });
      const data = await res.json().catch(() => null);

      if (!res.ok) throw new Error(data?.error || "Import failed");

      toast.success("YouTube video sync queued. Captions and questions are being processed.");
      setYoutubeUrl("");
      setYoutubePreview(null);
      onOpenChange(false);
      onSuccess();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "YouTube import failed");
    } finally {
      setYoutubeImporting(false);
    }
  }

  async function confirmDisconnect() {
    if (!disconnectItem) return;
    setDisconnecting(true);
    try {
      const res = await fetch(
        `/api/knowledge/connections/${disconnectItem.id}?provider=${disconnectItem.provider}`,
        { method: "DELETE" },
      );
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Disconnect failed");

      toast.success(
        `Disconnected ${disconnectItem.title}. Removed associated sources and documents.`,
      );
      setDisconnectItem(null);
      onSuccess();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Disconnect failed");
    } finally {
      setDisconnecting(false);
    }
  }

  const completedCount = queue.filter((q) => q.status === "done").length;
  const pendingCount = queue.filter((q) => q.status === "pending").length;

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent className="sm:max-w-xl max-h-[85vh] flex flex-col p-0 overflow-hidden">
          <DialogHeader className="p-6 pb-2">
            <DialogTitle>Add Knowledge Source</DialogTitle>
            <DialogDescription>
              Upload documents or connect external sources to ground your trainers.
            </DialogDescription>
          </DialogHeader>

          <Tabs value={activeTab} onValueChange={setActiveTab} className="flex flex-col flex-1 min-h-0">
            <div className="px-6 border-b">
              <TabsList className="grid w-full grid-cols-4">
                <TabsTrigger value="upload" className="gap-1.5 text-xs">
                  <Upload className="size-3.5" /> Upload
                </TabsTrigger>
                <TabsTrigger value="notion" className="gap-1.5 text-xs">
                  <BookOpen className="size-3.5" /> Notion
                </TabsTrigger>
                <TabsTrigger value="youtube" className="gap-1.5 text-xs">
                  <Video className="size-3.5" /> YouTube
                </TabsTrigger>
                <TabsTrigger value="connections" className="gap-1.5 text-xs">
                  <Link2 className="size-3.5" /> Connections
                </TabsTrigger>
              </TabsList>
            </div>

            <div className="flex-1 overflow-y-auto p-6 min-h-0">
              {/* TAB 1: FILE UPLOAD */}
              <TabsContent value="upload" className="m-0 space-y-4">
                <div
                  onDragOver={(e) => {
                    e.preventDefault();
                    setDragOver(true);
                  }}
                  onDragLeave={() => setDragOver(false)}
                  onDrop={(e) => {
                    e.preventDefault();
                    setDragOver(false);
                    if (e.dataTransfer.files) addFiles(e.dataTransfer.files);
                  }}
                  onClick={() => fileInputRef.current?.click()}
                  className={`flex flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed p-6 text-center cursor-pointer transition-colors ${
                    dragOver
                      ? "border-primary bg-primary/5"
                      : "border-muted-foreground/25 hover:border-primary/50 hover:bg-muted/40"
                  }`}
                >
                  <Upload className="size-8 text-muted-foreground" />
                  <div className="text-sm font-medium">Click to browse or drop files here</div>
                  <div className="text-xs text-muted-foreground">
                    PDF, DOCX, PPTX, CSV, TXT, MD up to 50MB
                  </div>
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    accept={ACCEPT_STRING}
                    onChange={(e) => {
                      if (e.target.files) addFiles(e.target.files);
                      e.target.value = "";
                    }}
                    className="hidden"
                  />
                </div>

                {queue.length > 0 && (
                  <div className="space-y-2">
                    <div className="flex items-center justify-between text-xs text-muted-foreground">
                      <span>Queue ({queue.length} files)</span>
                      <span>
                        {completedCount} of {queue.length} ready
                      </span>
                    </div>
                    <div className="max-h-48 space-y-1.5 overflow-y-auto pr-1">
                      {queue.map((item) => (
                        <div
                          key={item.id}
                          className="flex items-center justify-between gap-2 rounded-lg border bg-muted/30 px-3 py-2 text-xs"
                        >
                          <div className="flex min-w-0 items-center gap-2">
                            <FileText className="size-4 shrink-0 text-muted-foreground" />
                            <div className="min-w-0">
                              <p className="truncate font-medium">{item.file.name}</p>
                              <p className="text-[11px] text-muted-foreground">
                                {formatBytes(item.file.size)}
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2 shrink-0">
                            {item.status === "uploading" && (
                              <Spinner className="size-3.5 text-primary" />
                            )}
                            {item.status === "done" && (
                              <CheckCircle2 className="size-3.5 text-emerald-500" />
                            )}
                            {item.status === "error" && (
                              <span title={item.error}>
                                <AlertCircle className="size-3.5 text-destructive" />
                              </span>
                            )}
                            {!isUploading && item.status !== "done" && (
                              <button
                                type="button"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  removeItem(item.id);
                                }}
                                className="text-muted-foreground hover:text-foreground"
                              >
                                <X className="size-3.5" />
                              </button>
                            )}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </TabsContent>

              {/* TAB 2: NOTION */}
              <TabsContent value="notion" className="m-0 space-y-4">
                <div className="flex rounded-lg border bg-muted/40 p-1">
                  <button
                    type="button"
                    onClick={() => setNotionMode("oauth")}
                    className={`flex-1 rounded-md py-1.5 text-xs font-medium transition-all ${
                      notionMode === "oauth"
                        ? "bg-background text-foreground shadow-xs"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    Connected Workspace
                  </button>
                  <button
                    type="button"
                    onClick={() => setNotionMode("public")}
                    className={`flex-1 rounded-md py-1.5 text-xs font-medium transition-all ${
                      notionMode === "public"
                        ? "bg-background text-foreground shadow-xs"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    Public Page URL
                  </button>
                </div>

                {notionMode === "oauth" ? (
                  <div className="space-y-4">
                    {notionConnections.length === 0 ? (
                      <div className="rounded-xl border border-dashed p-6 text-center space-y-3">
                        <BookOpen className="size-8 mx-auto text-muted-foreground" />
                        <div className="space-y-1">
                          <p className="text-sm font-medium">No Notion workspace connected</p>
                          <p className="text-xs text-muted-foreground">
                            Connect your Notion workspace to import private and team pages with sub-pages.
                          </p>
                        </div>
                        <Button
                          onClick={startNotionOAuth}
                          size="sm"
                          disabled={!connectors?.notion.configured}
                        >
                          <Plus data-icon="inline-start" /> Connect Notion Workspace
                        </Button>
                        {!connectors?.notion.configured && (
                          <p className="text-[11px] text-destructive">
                            Notion OAuth client credentials are not configured in environment.
                          </p>
                        )}
                      </div>
                    ) : (
                      <div className="space-y-3">
                        <div className="space-y-1">
                          <label className="text-xs font-medium text-foreground">
                            Workspace
                          </label>
                          <select
                            value={notionConnectionId || selectedNotionConnection?.id}
                            onChange={(e) => setNotionConnectionId(e.target.value)}
                            className="w-full rounded-md border border-input bg-background px-3 py-1.5 text-xs shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                          >
                            {notionConnections.map((c) => (
                              <option key={c.id} value={c.id}>
                                {c.workspaceName || `Workspace (${c.workspaceId})`}
                              </option>
                            ))}
                          </select>
                        </div>

                        <div className="space-y-1">
                          <label className="text-xs font-medium text-foreground">
                            Notion Page URL or ID
                          </label>
                          <Input
                            placeholder="https://notion.so/my-org/Page-Title-1234567890abcdef"
                            value={notionUrl}
                            onChange={(e) => setNotionUrl(e.target.value)}
                            className="h-8 text-xs"
                          />
                          <p className="text-[11px] text-muted-foreground">
                            Child pages under this root page will be traversed and indexed automatically.
                          </p>
                        </div>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <label className="text-xs font-medium text-foreground">
                        Public Notion Page URL
                      </label>
                      <Input
                        placeholder="https://myorg.notion.site/Public-Page-1234567890abcdef"
                        value={notionUrl}
                        onChange={(e) => setNotionUrl(e.target.value)}
                        className="h-8 text-xs"
                      />
                      <p className="text-[11px] text-muted-foreground">
                        The page must be published to the web with public read access enabled.
                      </p>
                    </div>
                  </div>
                )}
              </TabsContent>

              {/* TAB 3: YOUTUBE */}
              <TabsContent value="youtube" className="m-0 space-y-4">
                {youtubeConnections.length === 0 ? (
                  <div className="rounded-xl border border-dashed p-6 text-center space-y-3">
                    <Video className="size-8 mx-auto text-muted-foreground" />
                    <div className="space-y-1">
                      <p className="text-sm font-medium">No YouTube channel connected</p>
                      <p className="text-xs text-muted-foreground">
                        Connect your YouTube channel to import video captions and extract training questions.
                      </p>
                    </div>
                    <Button
                      onClick={startYouTubeOAuth}
                      size="sm"
                      disabled={!connectors?.youtube.configured}
                    >
                      <Plus data-icon="inline-start" /> Connect YouTube Channel
                    </Button>
                    {!connectors?.youtube.configured && (
                      <p className="text-[11px] text-destructive">
                        YouTube OAuth credentials are not configured in environment.
                      </p>
                    )}
                  </div>
                ) : (
                  <div className="space-y-3">
                    <div className="space-y-1">
                      <label className="text-xs font-medium text-foreground">Channel</label>
                      <select
                        value={youtubeConnectionId || selectedYoutubeConnection?.id}
                        onChange={(e) => setYoutubeConnectionId(e.target.value)}
                        className="w-full rounded-md border border-input bg-background px-3 py-1.5 text-xs shadow-xs focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                      >
                        {youtubeConnections.map((c) => (
                          <option key={c.id} value={c.id}>
                            {c.channelTitle} ({c.channelId})
                          </option>
                        ))}
                      </select>
                    </div>

                    <div className="space-y-1">
                      <label className="text-xs font-medium text-foreground">
                        YouTube Video URL
                      </label>
                      <div className="flex gap-2">
                        <Input
                          placeholder="https://www.youtube.com/watch?v=..."
                          value={youtubeUrl}
                          onChange={(e) => {
                            setYoutubeUrl(e.target.value);
                            setYoutubePreview(null);
                          }}
                          className="h-8 text-xs flex-1"
                        />
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={handleYouTubePreview}
                          disabled={!youtubeUrl.trim() || youtubePreviewing}
                          className="h-8 text-xs shrink-0"
                        >
                          {youtubePreviewing ? (
                            <Spinner data-icon="inline-start" />
                          ) : (
                            <RefreshCw data-icon="inline-start" />
                          )}
                          Preview
                        </Button>
                      </div>
                    </div>

                    {youtubePreview && (
                      <div className="rounded-lg border bg-muted/30 p-3 space-y-2 text-xs">
                        <div className="font-semibold text-foreground truncate">
                          {youtubePreview.title}
                        </div>
                        <div className="flex flex-wrap items-center gap-2 text-muted-foreground">
                          <span>Channel: {youtubePreview.channelTitle}</span>
                          <span>•</span>
                          <span>Language: {youtubePreview.language}</span>
                          {youtubePreview.isAutoGenerated && (
                            <Badge variant="secondary" className="text-[10px]">
                              Auto-generated
                            </Badge>
                          )}
                          {youtubePreview.alreadyIndexed && (
                            <Badge variant="outline" className="text-[10px] border-amber-500/40 text-amber-600">
                              Already indexed (re-indexing will replace questions)
                            </Badge>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </TabsContent>

              {/* TAB 4: CONNECTIONS MANAGEMENT */}
              <TabsContent value="connections" className="m-0 space-y-4">
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      Notion Workspaces ({notionConnections.length})
                    </span>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={startNotionOAuth}
                      disabled={!connectors?.notion.configured}
                      className="h-7 text-xs"
                    >
                      <Plus data-icon="inline-start" /> Add Notion
                    </Button>
                  </div>

                  {notionConnections.length === 0 ? (
                    <p className="text-xs text-muted-foreground italic py-2">
                      No Notion workspaces connected.
                    </p>
                  ) : (
                    <div className="space-y-1.5">
                      {notionConnections.map((c) => (
                        <div
                          key={c.id}
                          className="flex items-center justify-between rounded-lg border p-2.5 text-xs bg-card"
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <BookOpen className="size-4 shrink-0 text-muted-foreground" />
                            <div className="min-w-0">
                              <p className="font-medium truncate">
                                {c.workspaceName || "Workspace"}
                              </p>
                              <p className="text-[11px] text-muted-foreground font-mono truncate">
                                {c.workspaceId}
                              </p>
                            </div>
                          </div>
                          <Button
                            variant="ghost"
                            size="icon-sm"
                            onClick={() =>
                              setDisconnectItem({
                                id: c.id,
                                title: c.workspaceName || "Notion Workspace",
                                provider: "notion",
                              })
                            }
                            className="size-7 text-destructive hover:bg-destructive/10"
                            title="Disconnect workspace"
                          >
                            <Trash2 className="size-3.5" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}

                  <div className="border-t pt-3 flex items-center justify-between">
                    <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                      YouTube Channels ({youtubeConnections.length})
                    </span>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={startYouTubeOAuth}
                      disabled={!connectors?.youtube.configured}
                      className="h-7 text-xs"
                    >
                      <Plus data-icon="inline-start" /> Add YouTube
                    </Button>
                  </div>

                  {youtubeConnections.length === 0 ? (
                    <p className="text-xs text-muted-foreground italic py-2">
                      No YouTube channels connected.
                    </p>
                  ) : (
                    <div className="space-y-1.5">
                      {youtubeConnections.map((c) => (
                        <div
                          key={c.id}
                          className="flex items-center justify-between rounded-lg border p-2.5 text-xs bg-card"
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <Video className="size-4 shrink-0 text-red-500" />
                            <div className="min-w-0">
                              <p className="font-medium truncate">{c.channelTitle}</p>
                              <p className="text-[11px] text-muted-foreground font-mono truncate">
                                {c.channelId}
                              </p>
                            </div>
                          </div>
                          <Button
                            variant="ghost"
                            size="icon-sm"
                            onClick={() =>
                              setDisconnectItem({
                                id: c.id,
                                title: c.channelTitle,
                                provider: "youtube",
                              })
                            }
                            className="size-7 text-destructive hover:bg-destructive/10"
                            title="Disconnect channel"
                          >
                            <Trash2 className="size-3.5" />
                          </Button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </TabsContent>
            </div>

            {/* DIALOG FOOTER */}
            <DialogFooter className="p-4 border-t bg-muted/20">
              {activeTab === "upload" && (
                <div className="flex items-center justify-between w-full">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setQueue([])}
                    disabled={queue.length === 0 || isUploading}
                  >
                    Clear
                  </Button>
                  <Button
                    size="sm"
                    onClick={startUpload}
                    disabled={pendingCount === 0 || isUploading}
                  >
                    {isUploading ? (
                      <Spinner data-icon="inline-start" />
                    ) : (
                      <Upload data-icon="inline-start" />
                    )}
                    Upload {pendingCount > 0 ? `(${pendingCount})` : ""}
                  </Button>
                </div>
              )}

              {activeTab === "notion" && (
                <div className="flex items-center justify-end w-full gap-2">
                  <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
                    Cancel
                  </Button>
                  <Button
                    size="sm"
                    onClick={handleNotionImport}
                    disabled={
                      notionImporting ||
                      !notionUrl.trim() ||
                      (notionMode === "oauth" && notionConnections.length === 0)
                    }
                  >
                    {notionImporting ? (
                      <Spinner data-icon="inline-start" />
                    ) : (
                      <Plus data-icon="inline-start" />
                    )}
                    Import Notion Page
                  </Button>
                </div>
              )}

              {activeTab === "youtube" && (
                <div className="flex items-center justify-end w-full gap-2">
                  <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
                    Cancel
                  </Button>
                  <Button
                    size="sm"
                    onClick={handleYouTubeImport}
                    disabled={
                      youtubeImporting || !youtubeUrl.trim() || youtubeConnections.length === 0
                    }
                  >
                    {youtubeImporting ? (
                      <Spinner data-icon="inline-start" />
                    ) : (
                      <Plus data-icon="inline-start" />
                    )}
                    {youtubePreview?.alreadyIndexed ? "Re-index Video" : "Import Video"}
                  </Button>
                </div>
              )}

              {activeTab === "connections" && (
                <div className="flex items-center justify-end w-full">
                  <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
                    Close
                  </Button>
                </div>
              )}
            </DialogFooter>
          </Tabs>
        </DialogContent>
      </Dialog>

      {/* DESTRUCTIVE DISCONNECT CONFIRMATION MODAL */}
      <Dialog
        open={Boolean(disconnectItem)}
        onOpenChange={(open) => !open && setDisconnectItem(null)}
      >
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-destructive flex items-center gap-2">
              <AlertCircle className="size-5" /> Disconnect {disconnectItem?.title}?
            </DialogTitle>
            <DialogDescription className="space-y-2 pt-2">
              <p>
                Disconnecting this integration will permanently delete all associated documents,
                extracted questions, vector embeddings, and cached files from your knowledge base.
              </p>
              <p className="font-semibold text-foreground">
                This action cannot be undone.
              </p>
            </DialogDescription>
          </DialogHeader>
          <DialogFooter className="gap-2 sm:gap-0">
            <Button
              variant="outline"
              size="sm"
              onClick={() => setDisconnectItem(null)}
              disabled={disconnecting}
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              size="sm"
              onClick={confirmDisconnect}
              disabled={disconnecting}
            >
              {disconnecting ? <Spinner data-icon="inline-start" /> : <Trash2 data-icon="inline-start" />}
              Confirm Disconnect
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
