"use client";

import { useRef, useState } from "react";
import {
  AlertCircle,
  BookOpen,
  CheckCircle2,
  ChevronRight,
  FileText,
  Plus,
  Trash2,
  Upload,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Spinner } from "@/components/ui/spinner";
import type { ConnectorInfo } from "./types";

type UploadQueueItem = {
  id: string;
  file: File;
  status: "pending" | "uploading" | "done" | "error";
  error?: string;
};

type YouTubePreviewData = {
  videoId: string;
  title: string;
  channelId: string;
  channelTitle: string;
  captionId: string;
  language: string;
  isAutoGenerated: boolean;
  captionUpdatedAt: string;
  alreadyIndexed: boolean;
};

type NavCategory = "popular" | "files" | "youtube" | "notion";

const SUPPORTED_EXTS = ["pdf", "docx", "doc", "pptx", "ppsx", "csv", "txt", "md"];
const ACCEPT_STRING =
  ".pdf,.docx,.doc,.pptx,.ppsx,.csv,.txt,.md,text/plain,text/markdown,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.presentationml.presentation,text/csv";

function formatBytes(n: number) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}

function YouTubeIcon({ className = "w-4 h-4" }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
    </svg>
  );
}

function NotionIcon({ className = "w-4 h-4" }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="currentColor">
      <path d="M4.459 4.208c.746.606 1.034.672 2.42.672h11.92c.26 0 .192-.032.434-.128.042-.032 0-.064-.13-.16l-1.47-1.184c-.52-.4-.86-.672-1.86-.672H6.536c-.78 0-.52.192.13.672l-2.207 1.8zm.78 2.016v12.704c0 .736.26 1.024 1.034 1.056l12.506.384c.78.032 1.034-.288 1.034-1.024V6.224c0-.736-.26-.992-.86-.96l-12.64.32c-.65.032-.994.288-.994.96zm11.726.8c.13.608 0 1.216-.608 1.28l-.52.064v9.152c-.434.224-.78.352-1.086.352-.52 0-.65-.16-1.034-.608l-3.172-4.992v4.832l1.002.224s0 1.216-1.69 1.216l-4.64-.288c-.13-.032-.26-.16-.26-.352.032-.224.26-.48.26-.48l1.212-.288V9.2l-1.69-.064C4.85 9.04 4.85 8.24 5.5 8.08l4.38-.288c.564 0 .65.16 1.086.608l3.042 4.8V8.8l-.78-.064c-.608-.064-.736-.672-.608-1.28l3.952.256.482.32z" />
    </svg>
  );
}

export function KnowledgeAddSourceDialog({
  open,
  onOpenChange,
  connectors,
  onSuccess,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  connectors?: ConnectorInfo;
  onSuccess: () => void;
}) {
  const [activeCategory, setActiveCategory] = useState<NavCategory>("popular");

  const [queue, setQueue] = useState<UploadQueueItem[]>([]);
  const [isUploading, setIsUploading] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [notionMode, setNotionMode] = useState<"oauth" | "public">("oauth");
  const [notionConnectionId, setNotionConnectionId] = useState("");
  const [notionUrl, setNotionUrl] = useState("");
  const [notionImporting, setNotionImporting] = useState(false);

  const [youtubeConnectionId, setYoutubeConnectionId] = useState("");
  const [youtubeUrl, setYoutubeUrl] = useState("");
  const [youtubePreviewing, setYoutubePreviewing] = useState(false);
  const [youtubePreview, setYoutubePreview] = useState<YouTubePreviewData | null>(null);
  const [youtubeImporting, setYoutubeImporting] = useState(false);

  const [disconnectItem, setDisconnectItem] = useState<{
    id: string;
    title: string;
    provider: "notion" | "youtube";
  } | null>(null);
  const [disconnecting, setDisconnecting] = useState(false);

  const notionConnections = connectors?.notion.connections ?? [];
  const youtubeConnections = connectors?.youtube.connections ?? [];
  const selectedNotionConnection =
    notionConnections.find((c) => c.id === notionConnectionId) ?? notionConnections[0];
  const selectedYoutubeConnection =
    youtubeConnections.find((c) => c.id === youtubeConnectionId) ?? youtubeConnections[0];

  function addFiles(files: FileList | File[]) {
    const newItems: UploadQueueItem[] = [];
    for (let i = 0; i < files.length; i++) {
      const file = files[i];
      const ext = file.name.split(".").pop()?.toLowerCase() || "";
      if (!SUPPORTED_EXTS.includes(ext)) {
        toast.error(`Unsupported format: ${file.name}`);
        continue;
      }
      newItems.push({
        id: `${file.name}-${Date.now()}-${i}`,
        file,
        status: "pending",
      });
    }
    setQueue((prev) => [...prev, ...newItems]);
  }

  function removeItem(id: string) {
    if (isUploading) return;
    setQueue((prev) => prev.filter((item) => item.id !== id));
  }

  async function startUpload() {
    if (queue.length === 0 || isUploading) return;
    setIsUploading(true);
    let successCount = 0;
    let failCount = 0;

    for (let i = 0; i < queue.length; i++) {
      const item = queue[i];
      if (item.status === "done") continue;

      setQueue((prev) =>
        prev.map((q, idx) => (idx === i ? { ...q, status: "uploading" } : q)),
      );

      try {
        const formData = new FormData();
        formData.append("file", item.file);

        const res = await fetch("/api/knowledge/upload", {
          method: "POST",
          body: formData,
        });
        const data = await res.json().catch(() => null);

        if (!res.ok) throw new Error(data?.error || "Upload failed");

        setQueue((prev) =>
          prev.map((q, idx) => (idx === i ? { ...q, status: "done" } : q)),
        );
        successCount++;
      } catch (err) {
        failCount++;
        setQueue((prev) =>
          prev.map((q, idx) =>
            idx === i
              ? {
                  ...q,
                  status: "error",
                  error: err instanceof Error ? err.message : "Upload failed",
                }
              : q,
          ),
        );
      }
    }

    setIsUploading(false);
    if (successCount > 0) {
      toast.success(
        `Uploaded ${successCount} file${successCount > 1 ? "s" : ""}. Processing in background.`,
      );
      onSuccess();
    }
    if (failCount > 0) {
      toast.error(`Failed to upload ${failCount} file${failCount > 1 ? "s" : ""}`);
    }
  }

  async function startNotionOAuth() {
    try {
      const res = await fetch("/api/connectors/notion/oauth/start", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to start Notion authorization");
      if (data.url) window.location.href = data.url;
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to connect Notion");
    }
  }

  async function startYouTubeOAuth() {
    try {
      const res = await fetch("/api/connectors/youtube/oauth/start", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to start YouTube authorization");
      if (data.url) window.location.href = data.url;
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to connect YouTube");
    }
  }

  async function handleNotionImport() {
    const url = notionUrl.trim();
    if (!url) {
      toast.error("Please enter a Notion page URL");
      return;
    }
    if (notionMode === "oauth" && !selectedNotionConnection) {
      toast.error("Please connect a Notion workspace first");
      return;
    }

    setNotionImporting(true);
    try {
      const body =
        notionMode === "oauth"
          ? { mode: "oauth", url, connectionId: selectedNotionConnection?.id }
          : { mode: "public", url };

      const res = await fetch("/api/knowledge/connectors/notion", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Import failed");

      toast.success("Notion sync queued. Page and child pages are being indexed.");
      setNotionUrl("");
      onOpenChange(false);
      onSuccess();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Notion import failed");
    } finally {
      setNotionImporting(false);
    }
  }

  async function handleYouTubePreview() {
    const url = youtubeUrl.trim();
    if (!url) {
      toast.error("Please enter a YouTube video URL");
      return;
    }
    if (!selectedYoutubeConnection) {
      toast.error("Please connect a YouTube channel first");
      return;
    }

    setYoutubePreviewing(true);
    setYoutubePreview(null);
    try {
      const res = await fetch("/api/knowledge/connectors/youtube/preview", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          connectionId: selectedYoutubeConnection.id,
          url,
        }),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Preview failed");
      setYoutubePreview(data);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "YouTube preview failed");
    } finally {
      setYoutubePreviewing(false);
    }
  }

  async function handleYouTubeImport() {
    const url = youtubeUrl.trim();
    if (!url || !selectedYoutubeConnection) return;

    setYoutubeImporting(true);
    try {
      const res = await fetch("/api/knowledge/connectors/youtube", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          connectionId: selectedYoutubeConnection.id,
          url,
          refresh: Boolean(youtubePreview?.alreadyIndexed),
        }),
      });
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Import failed");

      toast.success("YouTube video sync queued. Captions and questions are being processed.");
      setYoutubeUrl("");
      setYoutubePreview(null);
      onOpenChange(false);
      onSuccess();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "YouTube import failed");
    } finally {
      setYoutubeImporting(false);
    }
  }

  async function confirmDisconnect() {
    if (!disconnectItem) return;
    setDisconnecting(true);
    try {
      const res = await fetch(
        `/api/knowledge/connections/${disconnectItem.id}?provider=${disconnectItem.provider}`,
        { method: "DELETE" },
      );
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new Error(data?.error || "Disconnect failed");

      toast.success(
        `Disconnected ${disconnectItem.title}. Removed associated sources and documents.`,
      );
      setDisconnectItem(null);
      onSuccess();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Disconnect failed");
    } finally {
      setDisconnecting(false);
    }
  }

  const NAV_ITEMS: { id: NavCategory; label: string }[] = [
    { id: "popular", label: "Popular" },
    { id: "files", label: "Files" },
    { id: "youtube", label: "YouTube" },
    { id: "notion", label: "Notion" },
  ];

  const titles: Record<NavCategory, string> = {
    popular: "Popular",
    files: "Upload Files",
    youtube: "YouTube",
    notion: "Notion",
  };

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent
          showCloseButton={false}
          className="sm:max-w-4xl md:max-w-5xl h-[620px] max-h-[90vh] p-0 gap-0 overflow-hidden rounded-2xl border border-border/80 shadow-2xl bg-background"
        >
          <div className="flex h-full w-full">
            <aside className="w-56 shrink-0 border-r border-border/60 bg-muted/20 flex flex-col p-4 select-none">
              <div className="px-3 py-2 mb-2">
                <h3 className="text-sm font-semibold text-foreground/90 tracking-tight">Add Content</h3>
              </div>
              <nav className="flex-1 space-y-1">
                {NAV_ITEMS.map((item) => {
                  const isActive = activeCategory === item.id;
                  return (
                    <button
                      key={item.id}
                      type="button"
                      onClick={() => setActiveCategory(item.id)}
                      className={`w-full flex items-center justify-between px-3 py-2 text-sm rounded-lg text-left transition-colors relative ${
                        isActive
                          ? "text-foreground font-medium bg-accent/40 before:absolute before:left-0 before:top-1.5 before:bottom-1.5 before:w-1 before:rounded-full before:bg-orange-500"
                          : "text-muted-foreground hover:text-foreground hover:bg-muted/40"
                      }`}
                    >
                      <span>{item.label}</span>
                    </button>
                  );
                })}
              </nav>
            </aside>

            <div className="flex-1 flex flex-col overflow-hidden bg-background">
              <div className="flex items-center justify-between px-7 py-4 border-b border-border/40 shrink-0">
                <h2 className="text-base font-semibold text-foreground">{titles[activeCategory]}</h2>
                <button
                  type="button"
                  onClick={() => onOpenChange(false)}
                  className="w-8 h-8 rounded-full flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
                  aria-label="Close"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-7">
                {activeCategory === "popular" && (
                  <div className="space-y-4">
                    <div className="grid grid-cols-2 gap-3.5">
                      <button
                        type="button"
                        onClick={() => setActiveCategory("files")}
                        className="group flex items-center justify-between p-4 rounded-xl border border-border/70 bg-card hover:border-orange-500/50 hover:shadow-xs transition-all text-left"
                      >
                        <div className="flex items-center gap-3.5 min-w-0">
                          <div className="w-9 h-9 rounded-lg bg-orange-500/10 text-orange-600 flex items-center justify-center shrink-0">
                            <Upload className="w-5 h-5" />
                          </div>
                          <div className="min-w-0">
                            <div className="text-sm font-medium text-foreground">Upload files</div>
                            <div className="text-xs text-muted-foreground truncate mt-0.5">
                              PDF, Word, PowerPoint, Markdown, CSV, TXT
                            </div>
                          </div>
                        </div>
                        <ChevronRight className="w-4 h-4 text-muted-foreground group-hover:text-foreground shrink-0 ml-2 group-hover:translate-x-0.5 transition-transform" />
                      </button>

                      <button
                        type="button"
                        onClick={() => setActiveCategory("youtube")}
                        className="group flex items-center justify-between p-4 rounded-xl border border-border/70 bg-card hover:border-orange-500/50 hover:shadow-xs transition-all text-left"
                      >
                        <div className="flex items-center gap-3.5 min-w-0">
                          <div className="w-9 h-9 rounded-lg bg-red-500/10 text-red-600 flex items-center justify-center shrink-0">
                            <YouTubeIcon className="w-5 h-5" />
                          </div>
                          <div className="min-w-0">
                            <div className="text-sm font-medium text-foreground">YouTube</div>
                            <div className="text-xs text-muted-foreground truncate mt-0.5">
                              Connect a channel and import video transcripts
                            </div>
                          </div>
                        </div>
                        <ChevronRight className="w-4 h-4 text-muted-foreground group-hover:text-foreground shrink-0 ml-2 group-hover:translate-x-0.5 transition-transform" />
                      </button>

                      <button
                        type="button"
                        onClick={() => setActiveCategory("notion")}
                        className="group flex items-center justify-between p-4 rounded-xl border border-border/70 bg-card hover:border-orange-500/50 hover:shadow-xs transition-all text-left col-span-2"
                      >
                        <div className="flex items-center gap-3.5 min-w-0">
                          <div className="w-9 h-9 rounded-lg bg-foreground/5 text-foreground flex items-center justify-center shrink-0">
                            <NotionIcon className="w-5 h-5" />
                          </div>
                          <div className="min-w-0">
                            <div className="text-sm font-medium text-foreground">Notion</div>
                            <div className="text-xs text-muted-foreground truncate mt-0.5">
                              Connect a workspace or import a public page
                            </div>
                          </div>
                        </div>
                        <ChevronRight className="w-4 h-4 text-muted-foreground group-hover:text-foreground shrink-0 ml-2 group-hover:translate-x-0.5 transition-transform" />
                      </button>
                    </div>
                  </div>
                )}

                {activeCategory === "files" && (
                  <div className="space-y-6">
                    <input
                      ref={fileInputRef}
                      type="file"
                      multiple
                      accept={ACCEPT_STRING}
                      className="hidden"
                      onChange={(e) => {
                        if (e.target.files) addFiles(e.target.files);
                        e.target.value = "";
                      }}
                    />

                    <div
                      onDragOver={(e) => {
                        e.preventDefault();
                        setDragOver(true);
                      }}
                      onDragLeave={() => setDragOver(false)}
                      onDrop={(e) => {
                        e.preventDefault();
                        setDragOver(false);
                        if (e.dataTransfer.files) addFiles(e.dataTransfer.files);
                      }}
                      onClick={() => fileInputRef.current?.click()}
                      className={`border border-dashed rounded-2xl p-8 flex flex-col items-center justify-center text-center cursor-pointer transition-all ${
                        dragOver
                          ? "border-orange-500 bg-orange-500/5 shadow-inner"
                          : "border-border/80 hover:border-orange-500/60 hover:bg-orange-500/[0.02]"
                      }`}
                    >
                      <div className="flex items-center justify-center -space-x-3 mb-3">
                        <div className="w-12 h-14 rounded-lg bg-card border border-border shadow-xs -rotate-6 flex flex-col items-center justify-center p-1">
                          <span className="text-[9px] font-bold text-muted-foreground/80 tracking-wider">MD</span>
                          <div className="w-6 h-1 bg-muted rounded-full mt-1.5" />
                          <div className="w-4 h-1 bg-muted rounded-full mt-1" />
                        </div>
                        <div className="w-12 h-14 rounded-lg bg-card border border-border shadow-md z-10 flex flex-col items-center justify-center p-1">
                          <span className="text-[9px] font-bold text-red-500 tracking-wider">PDF</span>
                          <div className="w-6 h-1 bg-red-100 dark:bg-red-950/40 rounded-full mt-1.5" />
                          <div className="w-4 h-1 bg-muted rounded-full mt-1" />
                        </div>
                        <div className="w-12 h-14 rounded-lg bg-card border border-border shadow-xs rotate-6 flex flex-col items-center justify-center p-1">
                          <span className="text-[9px] font-bold text-blue-500 tracking-wider">DOC</span>
                          <div className="w-6 h-1 bg-blue-100 dark:bg-blue-950/40 rounded-full mt-1.5" />
                          <div className="w-4 h-1 bg-muted rounded-full mt-1" />
                        </div>
                      </div>
                      <div className="text-sm font-semibold text-foreground">Upload files</div>
                      <div className="text-xs text-muted-foreground mt-1">
                        <span className="text-orange-500 font-medium">Click to browse</span> or drag and drop
                      </div>
                      <div className="text-[11px] text-muted-foreground/70 mt-2">
                        PDF, Word (.docx), PowerPoint (.pptx), Markdown, CSV, TXT
                      </div>
                    </div>

                    {queue.length > 0 && (
                      <div className="space-y-2 border border-border/60 rounded-xl p-4 bg-muted/10">
                        <div className="flex items-center justify-between text-xs text-muted-foreground px-1 pb-1">
                          <span className="font-medium text-foreground">
                            {queue.length} file{queue.length > 1 ? "s" : ""} selected
                          </span>
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            className="h-6 text-xs text-muted-foreground hover:text-foreground"
                            onClick={() => setQueue([])}
                            disabled={isUploading}
                          >
                            Clear all
                          </Button>
                        </div>
                        <div className="max-h-40 overflow-y-auto space-y-2">
                          {queue.map((item) => (
                            <div
                              key={item.id}
                              className="flex items-center justify-between p-2.5 rounded-lg bg-card border border-border/70 text-xs"
                            >
                              <div className="flex items-center gap-2.5 min-w-0 flex-1 mr-3">
                                <FileText className="w-4 h-4 text-muted-foreground shrink-0" />
                                <div className="truncate font-medium text-foreground">{item.file.name}</div>
                                <span className="text-muted-foreground/70 shrink-0">
                                  {formatBytes(item.file.size)}
                                </span>
                              </div>
                              <div className="flex items-center gap-2 shrink-0">
                                {item.status === "uploading" && (
                                  <Spinner className="w-3.5 h-3.5 text-orange-500" />
                                )}
                                {item.status === "done" && (
                                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                )}
                                {item.status === "error" && (
                                  <span className="text-destructive font-medium truncate max-w-[120px]">
                                    {item.error || "Failed"}
                                  </span>
                                )}
                                {item.status === "pending" && !isUploading && (
                                  <button
                                    type="button"
                                    onClick={() => removeItem(item.id)}
                                    className="text-muted-foreground hover:text-foreground p-0.5"
                                  >
                                    <X className="w-3.5 h-3.5" />
                                  </button>
                                )}
                              </div>
                            </div>
                          ))}
                        </div>
                        <div className="pt-2 flex justify-end">
                          <Button
                            type="button"
                            onClick={startUpload}
                            disabled={isUploading || queue.every((i) => i.status === "done")}
                            className="bg-orange-500 hover:bg-orange-600 text-white gap-2 text-xs"
                          >
                            {isUploading ? (
                              <>
                                <Spinner className="w-3.5 h-3.5" />
                                Uploading...
                              </>
                            ) : (
                              <>
                                <Upload className="w-3.5 h-3.5" />
                                Upload {queue.filter((i) => i.status !== "done").length} File(s)
                              </>
                            )}
                          </Button>
                        </div>
                      </div>
                    )}
                  </div>
                )}

                {activeCategory === "youtube" && (
                  <div className="space-y-6">
                    <div>
                      <div className="flex items-center justify-between mb-3">
                        <div>
                          <div className="text-xs font-semibold text-foreground">YouTube Channels</div>
                          <div className="text-[11px] text-muted-foreground">
                            Connect your channel via Google OAuth to import videos and transcripts
                          </div>
                        </div>
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={startYouTubeOAuth}
                          disabled={!connectors?.youtube.configured}
                          className="text-xs gap-1.5 border-border"
                        >
                          <Plus className="w-3.5 h-3.5" />
                          Connect Channel
                        </Button>
                      </div>

                      {youtubeConnections.length === 0 ? (
                        <div className="p-4 rounded-xl border border-dashed border-border/80 bg-muted/10 text-center">
                          <YouTubeIcon className="w-7 h-7 text-muted-foreground/60 mx-auto mb-1.5" />
                          <div className="text-xs font-medium text-foreground">No YouTube Channel Connected</div>
                          <div className="text-[11px] text-muted-foreground mt-0.5">
                            Connect your owned channel to import videos, extract questions, and process transcripts.
                          </div>
                        </div>
                      ) : (
                        <div className="space-y-2">
                          {youtubeConnections.map((c) => (
                            <div
                              key={c.id}
                              className={`flex items-center justify-between p-3 rounded-xl border transition-colors ${
                                selectedYoutubeConnection?.id === c.id
                                  ? "border-orange-500/70 bg-orange-500/[0.02]"
                                  : "border-border/70 bg-card"
                              }`}
                            >
                              <div
                                className="flex items-center gap-2.5 cursor-pointer flex-1"
                                onClick={() => setYoutubeConnectionId(c.id)}
                              >
                                <div className="w-8 h-8 rounded-lg bg-red-500/10 text-red-600 flex items-center justify-center shrink-0">
                                  <YouTubeIcon className="w-4 h-4" />
                                </div>
                                <div>
                                  <div className="text-xs font-medium text-foreground">{c.channelTitle}</div>
                                  <div className="text-[10px] text-muted-foreground">ID: {c.channelId}</div>
                                </div>
                              </div>
                              <div className="flex items-center gap-2">
                                <Badge variant="outline" className="text-[10px] text-emerald-600 border-emerald-500/30">
                                  Active
                                </Badge>
                                <Button
                                  type="button"
                                  variant="ghost"
                                  size="icon-xs"
                                  className="text-muted-foreground hover:text-destructive"
                                  onClick={() =>
                                    setDisconnectItem({
                                      id: c.id,
                                      title: c.channelTitle,
                                      provider: "youtube",
                                    })
                                  }
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </Button>
                              </div>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Import Video Form - only show after connecting at least one channel */}
                    {youtubeConnections.length > 0 && (
                      <div className="space-y-3 pt-2 border-t border-border/50">
                        <div className="text-xs font-semibold text-foreground">Import Video</div>
                        <div className="flex gap-2">
                          <Input
                            type="url"
                            placeholder="https://www.youtube.com/watch?v=..."
                            value={youtubeUrl}
                            onChange={(e) => {
                              setYoutubeUrl(e.target.value);
                              setYoutubePreview(null);
                            }}
                            className="text-xs h-10 border-border/80"
                          />
                          <Button
                            type="button"
                            variant="outline"
                            onClick={handleYouTubePreview}
                            disabled={youtubePreviewing || !youtubeUrl.trim() || !selectedYoutubeConnection}
                            className="text-xs px-4 border-border shrink-0"
                          >
                            {youtubePreviewing ? <Spinner className="w-3.5 h-3.5" /> : "Preview"}
                          </Button>
                        </div>

                        {/* Video Preview Card */}
                        {youtubePreview && (
                          <div className="p-4 rounded-xl border border-border/80 bg-card space-y-3">
                            <div className="flex items-start justify-between gap-3">
                              <div>
                                <div className="text-xs font-semibold text-foreground line-clamp-2">
                                  {youtubePreview.title}
                                </div>
                                <div className="text-[11px] text-muted-foreground mt-0.5">
                                  Channel: {youtubePreview.channelTitle} • Language:{" "}
                                  {youtubePreview.language.toUpperCase()}
                                </div>
                              </div>
                              {youtubePreview.alreadyIndexed && (
                                <Badge variant="outline" className="text-[10px] text-amber-600 border-amber-500/40 shrink-0">
                                  Already Indexed
                                </Badge>
                              )}
                            </div>
                            <div className="flex justify-end pt-1">
                              <Button
                                type="button"
                                onClick={handleYouTubeImport}
                                disabled={youtubeImporting}
                                className="bg-orange-500 hover:bg-orange-600 text-white text-xs px-4"
                              >
                                {youtubeImporting ? (
                                  <>
                                    <Spinner className="w-3.5 h-3.5 mr-1.5" />
                                    Importing...
                                  </>
                                ) : youtubePreview.alreadyIndexed ? (
                                  "Refresh Video"
                                ) : (
                                  "Import Video"
                                )}
                              </Button>
                            </div>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )}

                {activeCategory === "notion" && (
                  <div className="space-y-6">
                    <div className="flex items-center gap-2 p-1 bg-muted/40 rounded-xl w-fit">
                      <button
                        type="button"
                        onClick={() => setNotionMode("oauth")}
                        className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-all ${
                          notionMode === "oauth"
                            ? "bg-background text-foreground shadow-xs"
                            : "text-muted-foreground hover:text-foreground"
                        }`}
                      >
                        Connected Workspace
                      </button>
                      <button
                        type="button"
                        onClick={() => setNotionMode("public")}
                        className={`px-3.5 py-1.5 rounded-lg text-xs font-medium transition-all ${
                          notionMode === "public"
                            ? "bg-background text-foreground shadow-xs"
                            : "text-muted-foreground hover:text-foreground"
                        }`}
                      >
                        Public Page URL
                      </button>
                    </div>

                    {notionMode === "oauth" ? (
                      <div className="space-y-5">
                        <div>
                          <div className="flex items-center justify-between mb-3">
                            <div>
                              <div className="text-xs font-semibold text-foreground">
                                Workspaces ({notionConnections.length})
                              </div>
                              <div className="text-[11px] text-muted-foreground">
                                Select an authorized Notion workspace
                              </div>
                            </div>
                            <Button
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={startNotionOAuth}
                              disabled={!connectors?.notion.configured}
                              className="text-xs gap-1.5 border-border"
                            >
                              <Plus className="w-3.5 h-3.5" />
                              Connect Notion
                            </Button>
                          </div>

                          {notionConnections.length === 0 ? (
                            <div className="p-4 rounded-xl border border-dashed border-border/80 bg-muted/10 text-center">
                              <BookOpen className="w-7 h-7 text-muted-foreground/60 mx-auto mb-1.5" />
                              <div className="text-xs font-medium text-foreground">No Workspace Connected</div>
                              <div className="text-[11px] text-muted-foreground mt-0.5">
                                Connect your Notion workspace to import private databases and pages.
                              </div>
                            </div>
                          ) : (
                            <div className="space-y-2">
                              {notionConnections.map((c) => (
                                <div
                                  key={c.id}
                                  className={`flex items-center justify-between p-3 rounded-xl border transition-colors ${
                                    selectedNotionConnection?.id === c.id
                                      ? "border-orange-500/70 bg-orange-500/[0.02]"
                                      : "border-border/70 bg-card"
                                  }`}
                                >
                                  <div
                                    className="flex items-center gap-2.5 cursor-pointer flex-1"
                                    onClick={() => setNotionConnectionId(c.id)}
                                  >
                                    <div className="w-8 h-8 rounded-lg bg-foreground/5 flex items-center justify-center font-bold text-xs shrink-0">
                                      {c.workspaceIcon || c.workspaceName?.[0] || "N"}
                                    </div>
                                    <div>
                                      <div className="text-xs font-medium text-foreground">
                                        {c.workspaceName || "Notion Workspace"}
                                      </div>
                                      <div className="text-[10px] text-muted-foreground">ID: {c.workspaceId}</div>
                                    </div>
                                  </div>
                                  <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon-xs"
                                    className="text-muted-foreground hover:text-destructive"
                                    onClick={() =>
                                      setDisconnectItem({
                                        id: c.id,
                                        title: c.workspaceName || "Notion Workspace",
                                        provider: "notion",
                                      })
                                    }
                                  >
                                    <Trash2 className="w-3.5 h-3.5" />
                                  </Button>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>

                        {/* Page URL input and import button - only show after connecting at least one workspace */}
                        {notionConnections.length > 0 && (
                          <>
                            <div className="space-y-2 pt-2 border-t border-border/50">
                              <label className="text-xs font-semibold text-foreground">Notion Page URL</label>
                              <Input
                                type="url"
                                placeholder="https://notion.so/my-org/Page-Title-1234567890abcdef"
                                value={notionUrl}
                                onChange={(e) => setNotionUrl(e.target.value)}
                                className="text-xs h-10 border-border/80"
                              />
                              <p className="text-[11px] text-muted-foreground">
                                Subpages linked underneath this root will be recursively fanned out and indexed.
                              </p>
                            </div>

                            <div className="pt-2 flex justify-end">
                              <Button
                                type="button"
                                onClick={handleNotionImport}
                                disabled={notionImporting || !notionUrl.trim()}
                                className="bg-orange-500 hover:bg-orange-600 text-white text-xs px-5"
                              >
                                {notionImporting ? (
                                  <>
                                    <Spinner className="w-3.5 h-3.5 mr-1.5" />
                                    Queuing Sync...
                                  </>
                                ) : (
                                  "Import Notion Content"
                                )}
                              </Button>
                            </div>
                          </>
                        )}
                      </div>
                    ) : (
                      <div className="space-y-4">
                        <div className="space-y-2">
                          <label className="text-xs font-semibold text-foreground">Public Notion Page URL</label>
                          <Input
                            type="url"
                            placeholder="https://myorg.notion.site/Public-Page-1234567890abcdef"
                            value={notionUrl}
                            onChange={(e) => setNotionUrl(e.target.value)}
                            className="text-xs h-10 border-border/80"
                          />
                          <p className="text-[11px] text-muted-foreground">
                            Works on any page where &quot;Share to web&quot; is turned on. No OAuth connection required.
                          </p>
                        </div>

                        <div className="pt-2 flex justify-end">
                          <Button
                            type="button"
                            onClick={handleNotionImport}
                            disabled={notionImporting || !notionUrl.trim()}
                            className="bg-orange-500 hover:bg-orange-600 text-white text-xs px-5"
                          >
                            {notionImporting ? (
                              <>
                                <Spinner className="w-3.5 h-3.5 mr-1.5" />
                                Queuing Sync...
                              </>
                            ) : (
                              "Import Notion Content"
                            )}
                          </Button>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {disconnectItem && (
        <Dialog open={Boolean(disconnectItem)} onOpenChange={(open) => !open && setDisconnectItem(null)}>
          <DialogContent className="sm:max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-destructive">
                <AlertCircle className="w-5 h-5" />
                Disconnect {disconnectItem.title}?
              </DialogTitle>
              <DialogDescription className="text-xs">
                This will permanently delete the integration credentials and remove all imported
                sources, documents, and associated vector chunks from your knowledge base. This
                action cannot be undone.
              </DialogDescription>
            </DialogHeader>
            <DialogFooter className="gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={() => setDisconnectItem(null)}
                disabled={disconnecting}
                className="text-xs"
              >
                Cancel
              </Button>
              <Button
                type="button"
                variant="destructive"
                onClick={confirmDisconnect}
                disabled={disconnecting}
                className="text-xs"
              >
                {disconnecting ? (
                  <>
                    <Spinner className="w-3.5 h-3.5 mr-1.5" />
                    Disconnecting...
                  </>
                ) : (
                  "Disconnect & Remove Content"
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </>
  );
}
