import type { ConnectionStore } from "./connection-store.server";
import { googleRequest, listOwnedChannels, type YouTubeConfig } from "./http.server";
import { createAuthorizedRequests } from "./tokens.server";
import { parseCaptionSrt, transcriptMarkdown } from "./captions";
import { YouTubeError, type ConnectionScope, type OwnedVideo, type OwnedTranscript } from "./types";

type Caption = { id: string; snippet: { language: string; trackKind: string; status: string; isDraft: boolean; lastUpdated: string } };

/** Official owner-only acquisition. Credentials and caption selection stay behind this interface. */
export function createYouTubeClient(store: ConnectionStore, config: YouTubeConfig) {
  const authorized = createAuthorizedRequests(store, config);
  async function inspectOwnedVideo(scope: ConnectionScope, videoId: string): Promise<OwnedVideo> {
    if (!/^[A-Za-z0-9_-]{11}$/.test(videoId)) throw new YouTubeError("INVALID_URL", "Invalid YouTube video URL");
    return authorized(scope, async (token, connection) => {
      const channels = await listOwnedChannels(token);
      if (!channels.some((channel) => channel.id === connection.channelId)) throw new YouTubeError("WRONG_CHANNEL", "Reconnect the channel that owns this video");
      const headers = { Authorization: `Bearer ${token}` };
      const videos = JSON.parse(await googleRequest("video-details", `https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${videoId}`, { headers })) as {
        items?: { id: string; snippet: { title: string; channelId: string; channelTitle: string } }[];
      };
      const video = videos.items?.[0];
      if (!video) throw new YouTubeError("NOT_FOUND", "Video is unavailable to this YouTube connection");
      if (video.snippet.channelId !== connection.channelId) throw new YouTubeError("NOT_OWNED", "Only videos owned by the connected channel can be imported");
      const captions = JSON.parse(await googleRequest("caption-list", `https://www.googleapis.com/youtube/v3/captions?part=snippet&videoId=${videoId}`, { headers })) as { items?: Caption[] };
      const candidates = (captions.items ?? []).filter(({ snippet }) => /^en(?:-|$)/i.test(snippet.language)
        && snippet.status === "serving" && !snippet.isDraft && ["standard", "asr"].includes(snippet.trackKind.toLowerCase()));
      candidates.sort((a, b) => Number(a.snippet.trackKind.toLowerCase() === "asr") - Number(b.snippet.trackKind.toLowerCase() === "asr")
        || Number(b.snippet.language === "en") - Number(a.snippet.language === "en") || a.id.localeCompare(b.id));
      const caption = candidates[0];
      if (!caption) throw new YouTubeError("NO_ENGLISH_CAPTIONS", "No English captions available. Add English captions in YouTube Studio, then retry.");
      return {
        videoId, title: video.snippet.title, channelId: connection.channelId, channelTitle: video.snippet.channelTitle,
        captionId: caption.id, language: caption.snippet.language, isAutoGenerated: caption.snippet.trackKind.toLowerCase() === "asr",
        captionUpdatedAt: caption.snippet.lastUpdated,
      };
    });
  }
  return {
    inspectOwnedVideo,
    async checkConnection(scope: ConnectionScope) {
      return authorized(scope, async (token, connection) => {
        if (!(await listOwnedChannels(token)).some((channel) => channel.id === connection.channelId)) {
          throw new YouTubeError("WRONG_CHANNEL", "Reconnect the channel that owns these imports");
        }
      });
    },
    async fetchOwnedEnglishTranscript(scope: ConnectionScope, videoId: string): Promise<OwnedTranscript> {
      const video = await inspectOwnedVideo(scope, videoId);
      const srt = await authorized(scope, (token) => googleRequest("caption-download",
        `https://www.googleapis.com/youtube/v3/captions/${encodeURIComponent(video.captionId)}?tfmt=srt`,
        { headers: { Authorization: `Bearer ${token}` } }));
      const segments = parseCaptionSrt(srt);
      return { ...video, segments, markdown: transcriptMarkdown(segments) };
    },
  };
}
