export type TranscriptSegment = { text: string; startSeconds: number; endSeconds: number };
export type OwnedVideo = {
  videoId: string;
  title: string;
  channelId: string;
  channelTitle: string;
  captionId: string;
  language: string;
  isAutoGenerated: boolean;
  captionUpdatedAt: string;
};
export type OwnedTranscript = OwnedVideo & { segments: TranscriptSegment[]; markdown: string };
export type ConnectionScope = { connectionId: string; orgId: string; userId: string };

export class YouTubeError extends Error {
  constructor(public readonly code: string, message: string, public readonly retryable = false) {
    super(message);
    this.name = "YouTubeError";
  }
}
